config/routes.rb
Rails.application.routes.draw do
  root to: 'users#user_show'
  devise_for :users
  resources :users
  resources :secret_codes
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.admin?
      can :manage, :all
    elsif user.user?
      cannot :manage, SecretCode
      cannot [:index, :destroy, :update], User
    end
  end
end

app/models/secret_code.rb
class SecretCode < ActiveRecord::Base
  belongs_to :user

  attr_accessor :code_count

  scope :available, -> { where(user_id: nil) }

  def self.generate
  	create(code: SecureRandom.hex(8))
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :secret_code, dependent: :nullify
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  attr_accessor :secret_code

  after_commit :associate_secret_code, on: :create

  # Used for creating default admin through seeds.
  def self.create_default_admin
    find_or_create_by!(email: Rails.application.secrets.admin_email) do |user|
      user.password = Rails.application.secrets.admin_password
      user.password_confirmation = Rails.application.secrets.admin_password
      user.admin!
    end
  end

  # Dfault role of all users will be user and can only be modified by admin user.
  def set_default_role
    self.role ||= :user
  end

  # Secret code once used to register get associated to that user and can not be further used.
  def associate_secret_code
    code = SecretCode.available.find_by_code(secret_code)
    code.try(:update_column, :user_id, id)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :redirect_if_seceret_code_is_invalid, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    flash[:warning] = exception.message
    redirect_to root_path
  end

  rescue_from ActionController::InvalidAuthenticityToken do |exception|
    flash[:warning] = "Invalid Session"
    redirect_to root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :secret_code])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name])
  end

  private

  def redirect_if_seceret_code_is_invalid
    if params[:user].try(:key?, :secret_code)
      secure_code_is_invalid = SecretCode.available.pluck(:code).exclude?(params[:user][:secret_code])
      if (params[:user][:secret_code].blank? || secure_code_is_invalid)
        redirect_to new_user_session_path, :alert => "Invalid Code"
      end
    end
  end

end

app/controllers/secret_codes_controller.rb
class SecretCodesController < ApplicationController

  before_action :authenticate_user!
  load_and_authorize_resource

  def index
  	@secret_codes = SecretCode.includes(:user).all
    @secret_codes = @secret_codes.paginate(page: params[:page], per_page: 10)
    @secret_code = SecretCode.new
  end

  def create
    count = params[:secret_code][:code_count].to_i
    count = count.zero? ? 1 : count
    count.times do
      SecretCode.generate
    end
  	redirect_to secret_codes_path, :notice => "Secret Code added."
  end

  def destroy
    secret_code = SecretCode.find(params[:id])
    secret_code.destroy
    redirect_to secret_codes_path, :notice => "Secret Code deleted."
  end

  private

  def secret_code_params
    params.require(:secret_code).permit(:code)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  load_resource except: :user_show

  def index
    authorize! :index, User
  end

  def show
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    authorize! :update, User
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    authorize! :destroy, User
    @user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  def user_show
    redirect_to current_user
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def code_create_options
  	[[1, 1], [10, 10], [20, 20], [50, 50], [100, 100]]
  end

end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.haml
= render partial: 'layouts/nav_links_for_auth'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Demo'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Demo'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/secret_codes/_secret_code.html.erb
<td>
  <%= secret_code.code %>
</td>
<td>
  <%= secret_code.user.try(:email) %>
</td>
<td>
  <%= link_to("Delete code", secret_code_path(secret_code), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') if current_user.admin? %>
</td>

app/views/secret_codes/index.html.erb
<div>
  <p><%= link_to('All Users', users_path) %></p> 
</div>
<div>
  <div class="row">
	  <%= form_for(@secret_code) do |f| %>
	    <%= f.select(:code_count, code_create_options, selected: 10) %>
	    <%= f.submit 'Add Secret Codes', :class => 'button-xs' %>
	  <% end %>
  </div>
</div>

<div class="container">
  <div class="row">
    <h3>Secret Codes</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @secret_codes.each do |secret_code| %>
            <tr>
              <%= render secret_code %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%= will_paginate @secret_codes, renderer: BootstrapPagination::Rails %>

app/views/secret_codes/new.html.erb
<div class="secretcodeform">
  <%= form_for(@secret_code) do |f| %>
    <h3>Create Secret Code</h3>
    <div class="row">
      <%= f.label :code %>
      <%= f.text_field :code %>
      <%= f.submit 'Add', :class => 'button right' %>
    </div>
  <% end %>
</div>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<% if can? :index, SecretCode %>
  <div>
    <p><%= link_to 'Secret Codes', secret_codes_path%> </p>
  </div>
<% end %>
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if can? :index, User %>
  <div>
    <p><%= link_to('All Users', users_path) %></p> 
  </div>
<% end %>
<div>
  <h3>User</h3>
  <p>First Name: <%= @user.first_name if @user.first_name %></p>
  <p>Last Name: <%= @user.last_name if @user.last_name %></p>
  <p>Role: <%= @user.role if @user.role %></p>
  <p>Email: <%= @user.email if @user.email %></p>
</div>